apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: aaa

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaa
  labels:
    app: aaa
    service: aaa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aaa
      service: aaa
  template:
    metadata:
      labels:
        app: aaa
        service: aaa
    spec:
      serviceAccountName: aaa
      
      containers:
      - name: aaa-container
        image: hhana982/aaa:1.<version>
        ports:
        - containerPort: 3000
        
        env: 