apiVersion: v1
kind: Service
metadata:
  name: aaa
  labels:
    app: aaa
    service: aaa
spec:
  selector:
    app: aaa
    service: aaa
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP